name: Build and Test
on:
  pull_request:
    branches: [main]
  workflow_call:
    inputs:
      distribute:
        type: boolean
        default: false
    secrets:
      CODECOV_TOKEN:
        required: true

env:
  DENO_DIR: ${{ github.workspace }}/.cache
  DENO_VER: "2.1.4"

jobs:
  coding-checks:
    name: "Coding Checks"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v4
      - name: "Setup cache"
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: deno-${{ hashFiles('deno.json', 'deno.lock') }}
      - name: "Setup Deno"
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VER }}
      - name: "Lint check"
        run: deno lint
      - name: "Format check"
        run: deno fmt --check
  unit-test:
    name: "Testing"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v4
      - name: "Setup cache"
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: deno-${{ hashFiles('deno.lock') }}
      - name: "Setup Deno"
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VER }}
      - name: "Run unit tests"
        run: make test
      - name: "Generate coverage reports"
        run: make coverage/lcov
      - name: "Report test results"
        if: success() || failure()
        uses: codecov/test-results-action@v1
        with:
          files: coverage/report.xml
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: "Report coverage"
        uses: codecov/codecov-action@v4
        with:
          files: coverage/lcov
          token: ${{ secrets.CODECOV_TOKEN }}
  compile:
    name: "Compile binaries"
    runs-on: ubuntu-latest
    if: ${{ inputs.distribute == true }}
    needs:
      - coding-checks
      - unit-test
    strategy:
      matrix:
        os: [darwin, linux]
        arch: [x86_64, aarch64]
    steps:
      - name: "Check out code"
        uses: actions/checkout@v4
      - name: "Setup cache"
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: deno-${{ hashFiles('deno.lock') }}
      - name: "Setup Deno"
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VER }}
      - name: "Compile ${{ matrix.os }}-${{ matrix.arch }}"
        run: make target/${{ matrix.os }}-${{ matrix.arch }}/andthen
      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: andthen.${{ matrix.os }}-${{ matrix.arch }}
          path: target/${{ matrix.os }}-${{ matrix.arch }}/andthen
