# Versions:
#   * amann/action-semantic-pull-request @ v5.5.3 == 0723387faaf9b38adef4775cd42cfd5155ed6017
name: Validate PR Conventions

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate conventional title/summary
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            chore
            deps
            docs
            feat
            fix
            revert
